[build]
builder = "nixpacks"

[deploy]
startCommand = "cd server && node index.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[variables]
NODE_ENV = "production" 